#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

ynh_clean_setup () {
	### Remove this function if there's nothing to clean before calling the remove script.
	true
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

# Retrieve arguments
domain=$YNH_APP_ARG_DOMAIN
path_url=$YNH_APP_ARG_PATH
is_public=$YNH_APP_ARG_IS_PUBLIC
server=$YNH_APP_ARG_SERVER
ram=$YNH_APP_ARG_RAM
port=$YNH_APP_ARG_PORT
op=$YNH_APP_ARG_OP
rcon=$YNH_APP_ARG_RCON
passwd=$YNH_APP_ARG_PASSWD
eula=$YNH_APP_ARG_EULA

app=$YNH_APP_INSTANCE_NAME

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================

final_path=/home/yunohost.app/$app
test ! -e "$final_path" || ynh_die --message="This path already contains a folder"

# Check web path availability
ynh_webpath_available $domain $path_url

# Register (book) web path
ynh_webpath_register --app=$app --domain=$domain --path_url=$path_url

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_app_setting_set $app domain $domain
ynh_app_setting_set $app path $path_url
ynh_app_setting_set $app is_public $is_public

#=================================================
# FIND AND OPEN A PORT
#=================================================

# Find a free port
port_test=$(ynh_find_port $port)
port_test1=$(ynh_find_port 25575)

# Open this port
yunohost firewall allow --no-upnp TCP $port_test 2>&1
yunohost firewall allow --no-upnp TCP $port_test1 2>&1

ynh_app_setting_set $app port_test $port_test
ynh_app_setting_set $app port_test1 $port_test1

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_print_info "Installing dependencies..."

ynh_install_app_dependencies $pkg_dependencies

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

ynh_app_setting_set $app final_path $final_path
# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source "$final_path" "$server"

#=================================================
# MODIFY A CONFIG FILE
#=================================================

ynh_replace_string "__RAM__" "$ram" "../conf/systemd.service"
ynh_replace_string "__PATH__" "$final_path" "../conf/systemd.service"

ynh_replace_string "__PORT__" "$port" "../conf/server.properties"
ynh_replace_string "__RCON__" "$rcon" "../conf/server.properties"
ynh_replace_string "__PASSWD__" "$passwd" "../conf/server.properties"
cp -a ../conf/server.properties $final_path/server.properties

ynh_replace_string "__OP__" "$op" "../conf/ops.txt"
cp -a ../conf/ops.txt $final_path/ops.txt

ynh_replace_string "__EULA__" "$eula" "../conf/eula.txt"
cp -a ../conf/eula.txt $final_path/eula.txt

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression --message="Configuring a systemd service..."

ynh_add_systemd_config
systemctl enable $app.service --quiet

#=================================================
# NGINX CONFIGURATION
#=================================================

# Create a dedicated nginx config
ynh_add_nginx_config

#=================================================
# CREATE DEDICATED USER
#=================================================

# Create a system user
ynh_system_user_create $app

#=================================================
# GENERIC FINALIZATION
#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

chown -R $app: $final_path

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..."

# Start a systemd service
ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# SETUP SSOWAT
#=================================================
ynh_script_progression --message="Configuring SSOwat..."

# Make app public if necessary or protect it
if [ $is_public -eq 1 ]
then
	ynh_permission_update --permission "main" --add "visitors"
fi

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression --message="Reloading nginx web server..."

ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
